# Generated by Django 3.2.3 on 2021-10-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatTitle', models.CharField(max_length=40, verbose_name='Название')),
                ('beatDescription', models.TextField(max_length=255, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentMakerStatus', models.BooleanField(verbose_name='Статус продавца')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.siteuser')),
                ('products', models.ManyToManyField(to='mainapp.Beat')),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.siteuser'),
        ),
    ]
