# Generated by Django 3.2.3 on 2021-10-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_siteuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('actual_price', models.PositiveIntegerField(verbose_name='Актуальная цена')),
                ('old_price', models.PositiveIntegerField(verbose_name='Старая цена')),
                ('sale_status', models.BooleanField(verbose_name='Наличие скидки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.siteuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Beat',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='mainapp.Product'),
        ),
    ]
