# Generated by Django 4.0 on 2022-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
