# Generated by Django 4.0 on 2022-01-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_siteuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetSellerStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requset_status', models.CharField(choices=[('AC', 'ACCEPTED'), ('DN', 'DENIED'), ('NC', 'NOT CHECKED')], default='NC', max_length=2, verbose_name='Состояние заявки')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания заявки')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.siteuser', verbose_name='Запросивший статус')),
            ],
        ),
    ]
