# Generated by Django 4.0 on 2022-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_getsellerstatusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='getsellerstatusrequest',
            name='commentary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий к заявке'),
        ),
    ]
