# Generated by Django 4.0 on 2022-01-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_getsellerstatusrequest_commentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getsellerstatusrequest',
            old_name='requset_status',
            new_name='request_status',
        ),
    ]
