# Generated by Django 4.0.1 on 2022-07-02 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Бонусные баллы '),
        ),

    ]
