# Generated by Django 4.0.1 on 2022-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_cart_options_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Общая цена'),
        ),
    ]
