# Generated by Django 4.0.1 on 2022-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_cartproduct_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Итого к оплате'),
        ),
    ]
