# Generated by Django 4.0.1 on 2022-07-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_siteuser_bonus_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releated_seller', to='mainapp.siteuser', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_owner', to='mainapp.siteuser', verbose_name='Покупатель'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('owner', 'seller')},
        ),
    ]
